Update action.yml

diff --git a/action.yml b/action.yml
--- a/action.yml
+++ b/action.yml
@@ -8,5 +8,8 @@ runs:
   using: composite
   steps:
     - shell: bash
-      # prettier-ignore
-      run: echo '::error::You need to use the reusable workflow! Check out the website for a short getting started guide. https://jcbhmr.github.io/runs-on-freebsd-latest/'; exit 1
+      run: |
+        echo '::error::You need to use the reusable workflow! \
+        Check out the website for a getting started guide. \
+        https://jcbhmr.github.io/runs-on-freebsd-latest/'
+        exit 1
